### PR TITLE
Fixed issues with @Nested tests and @Managed browsers

### PR DESCRIPTION
**Pull request by slu-it**
- Factory declaration on class level was not available in @Nested classes
- Class level Browsers were created multiple times

---
This change is [Reviewable](https://reviewable.io/reviews/testit-webtester/webtester2-core/51)

### CODE REVIEW

**Comment by slu-it** [comment]
Hm.. codecov has a point, there is at least one test missing ...

**Comment by bitterblue** [comment]
:lgtm:  
One missing case, I think, is a `@Nested` class containing a static managed browser field. Can't hurt to add that :)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/51#-:-KYjp9XD_-PqNvB2zeUz:bkg3m5y)*

**Comment by slu-it** [comment]
Added additional tests and found a new bug. When declaring tests like this:
```java
public class SomeUiTest {
    @Nested
    class NestedTests {
        @Managed
        Browser instanceBrowser;
        @Test
        void someTest(){
            assertThat(instanceBrowser).isNotNull();
        }
    }
}
```
The `instanceBrowser` would never be initialized because the test class model was wrongly created. The simplest fix was to remove the model from the context. Now the model is created fresh for every (nested) class. The performance impact is minimal - any UI action will be 10 times more costly than always creating a new model could ever be.

**Comment by slu-it** [comment]
"I think, is a `@Nested` class containing a static managed browser field. Can't hurt to add that :)"
This is not a valid usecase, since you can't have static fields within @Nested classes and @Nested classes can't be static.

**Comment by bitterblue** [comment]
Oh well, learned something new about junit: `@Nested` static classes are just ignored when running the surrounding test class. They can however be independently executed (at least in my version of IntelliJ, 2016.3.1). There will be nasty surprises when someone develops static `@Nested` classes and then the tests won't run during CI builds :-o

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/51#-:-KZMHqkNlorOl_3vGiPy:b5804u8)*

**Pull request merged**
