### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by slu-it**
- Replaced some unnecessary code with Lombok annotations
- Formatted some classes
- Added missing JavaDoc
- Renamed EventSystem implementation class
- Optimized logs in case of missing property files by differentiating between required and optional files

---

This change is [Reviewable](https://reviewable.io/reviews/testit-webtester/webtester2-core/39)

### CODE REVIEW

**Comment by bitterblue** [comment]
BTW, those long comment lines are hard to read on my laptop (it's only full HD). They wrap and look ugly in diff tools and Reviewable (-_-

---

Reviewed 72 of 72 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[webtester-core/src/main/java/info/novatec/testit/webtester/config/adapters/ClasspathPropertiesFileConfigurationAdapter.java, line 63 at r1](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/39#-KU3eIz14i11wD-ikkDs:-KU3eIz27Jw4cwmtj0OW:b5s32sa) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/13b0c556ed86224bc71e52e5efe685eac84d050d/webtester-core/src/main/java/info/novatec/testit/webtester/config/adapters/ClasspathPropertiesFileConfigurationAdapter.java#L63)):_

> ``` Java
>     public void logFileNotOnClasspath() {
>         if (required) {
>             log.warn(FILE_NOT_ON_CLASSPATH, propertyFilePath);
> ```

We should use different messages to make the more critical case of a missing required config file easier to spot in the log. Maybe it's enough to just add another placeholder to the message and fill in "REQUIRED" and "optional", respectively: "Could not load REQUIRED configuration file: ..."

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/39#-:-KU3gv67I-iHHR05IFo2:b-clwdch)_

**Comment by slu-it** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[webtester-core/src/main/java/info/novatec/testit/webtester/config/adapters/ClasspathPropertiesFileConfigurationAdapter.java, line 63 at r1](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/39#-KU3eIz14i11wD-ikkDs:-KUH55FWoA_hDCHi-kTy:ba3o3oi) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/13b0c556ed86224bc71e52e5efe685eac84d050d/webtester-core/src/main/java/info/novatec/testit/webtester/config/adapters/ClasspathPropertiesFileConfigurationAdapter.java#L63)):_
<details><summary>

<i>Previously, bitterblue (Axel Schüssler) wrote…</i></summary>



> We should use different messages to make the more critical case of a missing required config file easier to spot in the log. Maybe it's enough to just add another placeholder to the message and fill in "REQUIRED" and "optional", respectively: "Could not load REQUIRED configuration file: ..."
> </details>
> Ok, I'll add an additional message. I think it would be better rename required to recommended and have these 2 messages:
> 1. WARNING Recommended properties file {} wasn't found on the classpath - properties will not be merged into configuration. 
> 2. INFO Optional property filed {} wasn't found on the classpath - properties will not be merged into configuration.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/39)_

**Comment by slu-it** [comment]
Codecov result was expected because of the replacement of explicit constructors with generated ones - the actual logical coverage hasn't changed since the same constructors are used like prior to the change.
The only notable difference is the addition in a424a4aca7fada79cbdb4f6b112a95fad5d481e1 which is not tested because it only affects logging.

**Comment by bitterblue** [comment]
Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/39)_

**Pull request merged**
