### PR TITLE
Test optimization

### PR DESCRIPTION
**Pull request by slu-it**
- Increase test covarage (based on mutation testing)
- Refactore some tests to the inner class pattern
- Removed legacy class not really used or needed in v2 (TESTIT_HOME configuration adapter)

---

This change is [Reviewable](https://reviewable.io/reviews/testit-webtester/webtester2-core/10)

### CODE REVIEW

**Comment by bitterblue** [comment]
Reviewed 54 of 84 files at r1.
Review status: 52 of 83 files reviewed at latest revision, 1 unresolved discussion.

---

_[webtester-core/src/main/java/info/novatec/testit/webtester/browser/operations/JavaScriptExecutor.java, line 52 [r1]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/10#-KKd92tISPsbGHbGhK6P:-KKd92tJsy2tNyj7IBpM:-1769110509) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/48ce6695edadd7890b58cfa8dbfd8410385b2f77/webtester-core/src/main/java/info/novatec/testit/webtester/browser/operations/JavaScriptExecutor.java#L52)):_

> ``` Java
>      * @param fragment the target {@link PageFragment}
>      * @param parameters any of Boolean, Long, String, List, WebElement or null.
>      * @param <T> the type of the return value is cast to before returning
> ```

"the expected type of the return value"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/10)_

**Comment by bitterblue** [comment]
need coffee (-_-
... and Reviewable needs shortcut keys.

**Comment by bitterblue** [comment]
Reviewed 30 of 84 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[webtester-core/src/test/java/utils/TestUtils.java, line 20 [r2]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/10#-KKdIMtZoBBB1YHzzCy5:-KKdIMt_S0m8IFOdqsUU:-823141607) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/def1b4084adb3f7e201d6fa123e9f05199a0fa72/webtester-core/src/test/java/utils/TestUtils.java#L20)):_

> ``` Java
> 
>     public static void setFieldValue(Object object, String fieldName, Object value)
>         throws NoSuchFieldException, IllegalAccessException {
> ```

I would wrap those checked exceptions in RuntimeErrors. That way, they won't pollute test method signatures.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/10)_

**Comment by slu-it** [comment]
Nice Sunday.. little coding - little dark souls 3 :)
Added optimizations from review.

**Comment by bitterblue** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/10)_

**Pull request merged**
