### PR TITLE
JUnit 5 support module

### PR DESCRIPTION
**Pull request by slu-it**
This is still a work in progress but there's already a lot of code.
I'd like some feedback, please.

---

This change is [Reviewable](https://reviewable.io/reviews/testit-webtester/webtester2-core/18)

### CODE REVIEW

**Comment by slu-it** [comment]
hm.. codacy doesn't allow for excluding tests via pattern and i can only exclude test folders once they are present on the master branche ... so I'll just ignore them for now..

**Comment by slu-it** [comment]
Ok, now it's finally ready for review - production and test code is working.
I'll write the documentation after the discussion about the core concepts, names etc. is done.

**Comment by slu-it** [comment]
@bitterblue I added an additional extension which will allow for the definition of entry points for browsers.
These can be defined by annotating a @Managed with @EntryPoint. The URLs are opened for the browser before each test and can include variables which will be resolved against the browser's configuration.

**Comment by slu-it** [comment]
Something seams strange with the codecov/path and /project values ... when executing the tests for the support module in the IDE the coverage is about 96% maybe jacoco has a problem with JUnit 5 ?

**Comment by bitterblue** [comment]
Could this be the same issue the Junit5 developers ran into? See: https://github.com/junit-team/junit5/issues/240
I'll have a look at the new extension on Friday or this weekend.

**Comment by slu-it** [comment]
No, I found the issue earlier today - I forgot to override the maven surefire plugin configuration to include integration tests which are normally excluded and executed by the failsafe plugin. But JUnit 5 tests are not supported by the failsafe plugin, yet.

**Comment by nt-ca-aqe** [comment]
Renamed TypedConfigurationValueGetter to ConfigurationUnmarshaller and added documentation.
Now this is no longer WIP >> please review and merge :)
-- slu-it

**Comment by bitterblue** [comment]
Currently reviewing, and I love how the extension concept of junit5 works out for us :)

Regarding overall design, I'm a bit unhappy about the coupling of the four actual extensions via the `TestClassModel` and the fact that we initialize it once in a fifth extension, and then share it among the others. The coupling is acceptable, since it's just a small library. But the shared state forces us to depend on annotation evaluation order in `EnableWebTesterExtensions`, which is ugly. And the user can no longer safely pick and choose the extensions she wants. Couldn't we initialize the model in the `BaseExtension`, but only if it's not already stored in the context? This would also eliminate the need for `setModel()`.

**Comment by slu-it** [comment]
We could lazy load the model, yes. That way the first extension actually needing it would trigger the load. As far as i know the context store is thread safe, so there should not be a problem.

**Comment by bitterblue** [comment]
I think that's the way to go then. I'd code this up in a separate issue so we can get this merge done first.

**Comment by bitterblue** [comment]
Reviewed 2 of 54 files at r1, 1 of 9 files at r4, 7 of 16 files at r5, 1 of 32 files at r6, 1 of 5 files at r7, 7 of 27 files at r8, 9 of 12 files at r9, 1 of 1 files at r10, 8 of 8 files at r11, 1 of 1 files at r12, 16 of 50 files at r13, 34 of 34 files at r14.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java, line 36 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4D5vu-eNPKtBTpPtX:-KP4D5vvEaKnEcVh6u0H:b-wbbzq) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java#L36)):_

> ``` Java
> @ExtendWith(EntryPointExtension.class)
> public @interface EnableWebTesterExtensions {
>     /* The order of @ExtendWith is relevant! The extensions are evaluated in the order they are defined in. */
> ```

Yes, we should address this as a separate issue.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/exceptions/UnknownConfigurationKeyException.java, line 17 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOkxJAKTLK-NQTtT8XK-r14-17:-KP4GF-FfckRfbAav-P7:b-or3r0z) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/exceptions/UnknownConfigurationKeyException.java#L17)):_
<details><summary>

<i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary>



> Codacy Issue found: [Perhaps 'key' could be replaced by a local variable.](https://www.codacy.com/app/github_64/webtester2-core/file/3267140963/issues/source?bid=3285379&fileBranchId=3472116#l17)
> </details>
> Is there a reason we want to keep key around?

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/BaseExtension.java, line 35 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP-01WR2wBzFaeJ3lQf:-KP-01WS3xGRRx1xT2xM:b-2fleb8) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/BaseExtension.java#L35)):_

> ``` Java
> 
>     protected BaseExtension(ReflectionUtils reflectionUtils) {
>         // can only be used by subclasses
> ```

Confused by this comment. Everything here is protected or private, so I'm not sure if it's just stating the obvious.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/analysis/TestClassAnalysisExtension.java, line 13 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP-4HwteXKq2n2iCDnt:-KP-4HwteXKq2n2iCDnu:bl1vrtf) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/analysis/TestClassAnalysisExtension.java#L13)):_

> ``` Java
> /**
>  * This {@link Extension} analyzes the test class and extracts a {@link TestClassModel} from that analysis. This model is
>  * then stored within the current test context to bes used by other extensions.
> ```

Typo: bes -> be

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java, line 63 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP-9cU3W54ZfMNHcfur:-KP-9cU4R6v28-bLE2zd:b1lwu48) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java#L63)):_

> ``` Java
>  *     String value;
>  *
>  *     &#64;ConfigurationValue(value="keys.foo", using=FooGetter.class)
> ```

FooGetter.class should also be an `Unmarshaller`

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java, line 91 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP-9q1hP0h9TC6qRXK-:-KP-9q1hP0h9TC6qRXK0:bz6u1yu) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java#L91)):_

> ``` Java
> 
>     @SuppressWarnings("unchecked")
>     private static final List<ConfigurationUnmarshaller<?>> DEFAULT_VALUE_GETTERS = new LinkedList() {{
> ```

DEFAULT_VALUE_GETTERS --> DEFAULT_UNMARSHALLERS

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java, line 137 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4GnGaM-24Qr3AA9Mw:-KP4GnGbGsJEybN4fM5V:b-fqyjtw) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java#L137)):_

> ``` Java
> 
>             Object value = null;
>             if (NoOpUnmarshaller.class.equals(annotation.using())) {
> ```

Maybe turn `NoOpUnmarshaller` into `DefaultUnmarshaller`, then move `getValueUsingDefaultGetters()` to that class. That would make this conditional unnecessary.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/unmarshaller/ConfigurationUnmarshaller.java, line 13 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4Hq3aEC0kF_WR_cYk:-KP4Hq3bR0Of1ANgSW0I:b-gotb96) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/unmarshaller/ConfigurationUnmarshaller.java#L13)):_

> ``` Java
>  * Implementations of this interface are used to unmarshal a value from a {@link Configuration} as a specific type.
>  * <p>
>  * More specifically these implementations are user when resolving values for fields annotated with {@link
> ```

Typo: user -> used

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java, line 21 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOzyS8hjui_qke_5YM6:-KOzyS8i6fEvPDOG867k:b9h8cem) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java#L21)):_

> ``` Java
>     }
> 
>     public Deque<Class<?>> getClassHierarchy(Class<?> testClass) {
> ```

Nitpicky, but I'd call this `getClassLineage()`. Hierarchy also includes subclasses and sibling classes (the entire inheritance tree).

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java, line 22 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOzxvv1Nc2sZNJUDXTf:-KOzxvv1Nc2sZNJUDXTg:b-x1td1b) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java#L22)):_

> ``` Java
> 
>     public Deque<Class<?>> getClassHierarchy(Class<?> testClass) {
>         Deque<Class<?>> classes = new LinkedList<>();
> ```

`Deque` and `LinkedList` are somewhat exotic. You want to get the list in reverse for convenience, don't you? Why not just use `Collections.reverse()` on an `ArrayList`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18)_

**Comment by slu-it** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java, line 36 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4D5vu-eNPKtBTpPtX:-KP4dwLW3HSj5Xm3yeKU:b-6a35bj) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java#L36)):_
<details><summary>

<i>Previously, bitterblue (Axel Schüssler) wrote…</i></summary>



> Yes, we should address this as a separate issue.
> </details>
> The comment itself is not in relation to the discussed issue. Its more like a general notice for future extensions how JUnit 5 handles extensions in general. In addition event with lazy loading of the model, we will always have a dependency between certain extensions. Without the ManagedBrowserExtension none of the other ones work, because the Browser fields would not be initialized.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/exceptions/UnknownConfigurationKeyException.java, line 17 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOkxJAKTLK-NQTtT8XK-r14-17:-KP4eZCVr7TJS3i1Kpym:b-jllchw) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/exceptions/UnknownConfigurationKeyException.java#L17)):_
<details><summary>

<i>Previously, bitterblue (Axel Schüssler) wrote…</i></summary>



> Is there a reason we want to keep key around?
> </details>
> (1) Codacy doesn't know about Lombok.
> (2) I tend to write my exceptions to remember data they were caused by. Maybe whoever catches the exception can use the key in some way. It might very well be that no one ever needs to get the key... but I'm not certain of it.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java, line 137 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4GnGaM-24Qr3AA9Mw:-KP4fKqviqrdx1pyHYFj:b-s6cncx) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/extensions/configuration/ConfigurationValueExtension.java#L137)):_
<details><summary>

<i>Previously, bitterblue (Axel Schüssler) wrote…</i></summary>



> Maybe turn `NoOpUnmarshaller` into `DefaultUnmarshaller`, then move `getValueUsingDefaultGetters()` to that class. That would make this conditional unnecessary.
> </details>
> Thats a great idea!

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java, line 22 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOzxvv1Nc2sZNJUDXTf:-KP4fa1NfOe13DIRR4S5:bxl1fdp) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java#L22)):_
<details><summary>

<i>Previously, bitterblue (Axel Schüssler) wrote…</i></summary>



> `Deque` and `LinkedList` are somewhat exotic. You want to get the list in reverse for convenience, don't you? Why not just use `Collections.reverse()` on an `ArrayList`?
> </details>
> Hm that actually an interesting topic - I don't know why or when it happened, but my default go to list has always been the LinkedList. I Generally use ArrayList only in cases where I'm sure data will be accessed by index instead of iterated over.
> To use the Dequeue side of LinkedList came to be because Stack should no longer be used and I wanted to "stack" the classes according to their lineage.
> But back to the issue at hand... Instead of an `ArrayList` with `Collections.reverse()` I could just return `List` instead of `Dequeue`. The `LinkedList` offers the push method and implements a `List`\- which doesn't need to be reversed at all.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18)_

**Comment by slu-it** [comment]
With the latest version I should have fixed all but one of the Reviewable Issues.

I have a problem moving the default unmarshaller code (static list, and impl) to the `DefaultUnmarshaller` class.
The interface doesn't really allow for the 1:n delegation to all of the default unmarshallers (String, Boolean etc.) without storing some state when `canHandle(..)` is called. Which was rather nasty in my first draft.
Just moving the list and method to the class, would not get rid of the ìf(...){...} else {...}` as intended.

I would suggest that we remember the issue and come up with a solution when changing the extension coupling...

**Comment by bitterblue** [comment]
Reviewed 1 of 16 files at r5, 2 of 52 files at r13, 2 of 36 files at r14, 7 of 12 files at r15.
Review status: 49 of 53 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java, line 36 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KP4D5vu-eNPKtBTpPtX:-KP7GoGMyvUvMWErqtIQ:b-bj3y2l) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/EnableWebTesterExtensions.java#L36)):_
<details><summary>

<i>Previously, slu-it (Stefan Ludwig) wrote…</i></summary>



> The comment itself is not in relation to the discussed issue. Its more like a general notice for future extensions how JUnit 5 handles extensions in general. In addition event with lazy loading of the model, we will always have a dependency between certain extensions. Without the ManagedBrowserExtension none of the other ones work, because the Browser fields would not be initialized.
> </details>
> Ah, I didn't think of that additional order dependency.

---

_[webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java, line 22 [r14]](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-KOzxvv1Nc2sZNJUDXTf:-KP7JSVEtfiVKRdlUnw4:b-p9rc8o) ([raw file](https://github.com/testit-webtester/webtester2-core/blob/66a3633259f589ad582f9ac8c1a81c29a69b81a4/webtester-support-junit5/src/main/java/info/novatec/testit/webtester/junit5/internal/ReflectionUtils.java#L22)):_
<details><summary>

<i>Previously, slu-it (Stefan Ludwig) wrote…</i></summary>



> Hm that actually an interesting topic - I don't know why or when it happened, but my default go to list has always been the LinkedList. I Generally use ArrayList only in cases where I'm sure data will be accessed by index instead of iterated over.
> To use the Dequeue side of LinkedList came to be because Stack should no longer be used and I wanted to "stack" the classes according to their lineage.
> But back to the issue at hand... Instead of an `ArrayList` with `Collections.reverse()` I could just return `List` instead of `Dequeue`. The `LinkedList` offers the push method and implements a `List`\- which doesn't need to be reversed at all.
> </details>
> OK. That makes the method signature more readable.

Regarding `LinkedList`, the general advice to Java developers is to avoid it and use `ArrayList` instead. From the top of my head, two reasons are:
- the two implementations have vastly different runtime behavior and the `List` interface hides that, which can lead to nasty surprises
- `ArrayList` maps really well to cache hierarchies of modern CPUs and tends to vastly outperform `LinkedList` for most use-cases (including this one)

Let's discuss this sometime :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18)_

**Comment by bitterblue** [comment]
LGTM

---

Reviewed 1 of 9 files at r4, 1 of 52 files at r13, 1 of 36 files at r14, 5 of 12 files at r15.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/testit-webtester/webtester2-core/18#-:-KP7RdsagWn4otS8M7um:bb6ywmx)_

**Comment by bitterblue** [comment]
I added #20 and #21 to address the design issues brought up in this discussion.

**Pull request merged**
